### ISSUE TITLE
"Edit this page on GitHub" does not work

### ISSUE THREAD

**Issue by john-light** [micro-btc/micro-btc-docs#2]
On each page there is a link: `Edit this page on GitHub`

However the link goes to a page that doesn't exist:

![Screenshot 2022-12-12 130918](https://user-images.githubusercontent.com/9424721/207121761-b593a981-5fa2-4f1e-b6c2-68e406f7929d.png)

**Comment by shea256** [comment]
Ah thanks! Looks like we need to insert a "/blob/master" in the middle of the links.

From this:

https://github.com/micro-btc/micro-btc-docs/src/pages/docs/getting-started.mdx

To this:

https://github.com/micro-btc/micro-btc-docs/blob/master/src/pages/docs/getting-started.mdx

We'll make the fix shortly, thanks again!

**Comment by john-light** [comment]
It is also linking to a page with a `.md` file while the actual files are `.mdx` files

**Comment by shea256** [comment]
Can you show me where you're seeing that? I cannot reproduce it. For me I'm getting `.md` links.

**Comment by john-light** [comment]
@shea256 you can see in the screenshot in the OP that the link that opened was a `.md` file. That was specifically from the "build with bitcoin" blog page https://www.micro-btc.dev/blog/build-with-bitcoin

**Comment by shea256** [comment]
@john-light just pushed through a fix. can you try this again and confirm it works?

**Comment by john-light** [comment]
LGTM
